require './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # Turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

desc "Start the server"
task :server do
  if ActiveRecord::Base.connection.migration_context.needs_migration?
    puts(">>>>>>>>>><<<<<<<<<")
    puts "Migrations are pending. Ensure to run `rake db:migrate` first"
    return
  end
  #enables one to run rake server to start server
  exec "rerun -b 'rackup config.ru'"
end
